version: "3.9"
services:
  bsm-mysql:
    container_name: bsm-mysql
    image: mysql:8.0
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstoremanagement
    ports:
      - 39062:3306
  bsm-be:
    image: golang:1.20.7-bookworm
    container_name: bsm-be
    volumes:
      - ./backend:/data
      - ./backend/static:/data/static
      - $HOME/.aws:/root/.aws
    working_dir: /data
    environment:
      - GOMEMLIMIT=5120MiB
    entrypoint: "/bin/bash\n -c /data/go-server.sh"
    ports:
      - 8080:8080
    depends_on:
      - bsm-mysql
    links:
      - bsm-mysql
