name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.22"]
        node-version: ["20.10.0"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - node-version: "20.10.0"
            next-env: "production"

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Node.js for Next.js frontend
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Go backend
        run: |
          cd backend
          go build -v ./...

      - name: Install dependencies for Next.js frontend
        run: |
          cd frontend
          npm install

      - name: Build Next.js frontend
        run: |
          cd frontend
          NEXT_PUBLIC_ENVIRONMENT=${{ matrix.next-env }} npm run build
